### ISSUE TITLE
Bonus token display may be incorrect

### ISSUE THREAD

**Issue by bloopd** [EtherFlip/etherflip-electron#10]
The Ropsten game in the screenshot:

https://ropsten.etherscan.io/tx/0xac2d167ad12ba16bafd8cb7291f184aded3fe28e8872857a84f7fbebeac5f785

displays +1 ETIX and +20 FUCK, however the transaction does not show any FUCKs given. ;)

BTW, love that more than one token can be displayed and that it shows up in "My Games" now too.

[
![etherflip_aug07_01](https://user-images.githubusercontent.com/42195069/43814212-61d3e796-9a86-11e8-9232-d02a36b0407b.png)
](url)

**Comment by EtherFlip** [comment]
Closing this as this only occurs on Ropsten due to inconsistent token listings between Mainnet and Ropsten. Mainnet is not affected
